language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -e '.[testing]'
script:
  - rm -rf .mypy_cache || true
  - mypy typecov.py test_typecov.py
  - python -m typecov 100 .typecov/report/linecount.txt
  - typecov 100 .typecov/report/linecount.txt
  - pytest --cov=typecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
